[build]
  command = "expo export -p web"
  publish = "dist"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/_expo/static/js/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
